### ISSUE TITLE
Can not install Qprompt - missing requirements.txt

### ISSUE THREAD

**Issue by BartlomiejBartnicki** [jeffrimko/Qprompt#11]
Can not install package by pip:
>pip install qprompt-0.14.0.tar.gz
Processing qprompt-0.14.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "...Temp\pip-req-build-ud9nuave\setup.py", line 14, in <module>
        install_requires=open("requirements.txt").read().splitlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

Installing by python setup.py install also raise same exception
Workaround is to create empty requirements.txt file.

**Comment by jeffrimko** [comment]
Should be fixed in new release `0.14.1`. Thanks for reporting!
